### ISSUE TITLE
Contacts app shows user id instead of display name for the members

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/circles#604]
![Bildschirmfoto von 2021-06-01 21-54-52](https://user-images.githubusercontent.com/213943/120382634-290eb200-c324-11eb-92fc-f909566138bc.png)

cc @daita

**Comment by daita** [comment]
_but you can call me e404_

**Comment by daita** [comment]
This is fixed on `master`:

- run `./occ circles:maintenance --level 5` to upgrade all `displayName`
- editing an Account should upgrade the displayName of the Single Circle and all Members related to the UserId/FederatedUser
- should also works in GlobalScale setup

**Comment by albanbruder** [comment]
For me, the problem still exists. (NC23)

When I add a user to a circle, username/userId is used as displayName. But when the user updates their display name, the userId is replaced with the display name.

So it seems that the cache is not initialized properly.

**Comment by fonata** [comment]
I have added `./occ circles:maintenance --level 5` to my crontab. Is this supposed to be triggered by the main cron.php from Nextcloud? At least in our Nextcloud 25.0.1 with Circles 25.0.0, names remained strange for weeks, even though cron.php is triggered once every 5 minutes.
